version: 0.2

phases:
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - lein uberjar
      - mv target/unisporter.jar .
      - rm -rf target src test buildspec.yml project.clj
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.json
artifacts:
  files:
    - unisporter.jar
    - template-export.json
