version: 0.2


env:
  variables:
    BUILD: "true"
phases:
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - chmod 755 bin/lein
      - bin/lein do compile, libdir
      - mv target/classes/* ./
      - rm -rf src target test
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.json
artifacts:
  files:
    - template-export.json

