version: 0.2

phases:
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - bin/lein uberjar
      - mv target/classes/* .
      - rm -rf target src test resources buildspec.yml project.clj
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.json
artifacts:
  files:
    - target/unisporter.jar
    - template-export.json
