  {{ lambda-name }}:
    Type: AWS::Serverless::Function
    Properties:
      Handler: {{ handler }}
      Runtime: java8
      MemorySize: 512
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Environment:
        Variables:
          {% for e in environment }}"{{ e|key }}": "{{ e|val }}"
          {% endfor %}
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: {{ path }}
            Method: {{ method }}

