  {{ lambda-name }}:
    Type: AWS::Serverless::Function
    Properties:
      Handler: {{ handler }}
      Runtime: java8
      MemorySize: 512
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: {{ path }}
            Method: {{ method }}

